These peculiar transformations in social science
curiously precede the period of remarkable, worldwide economic
integration which has come to be known as globalisation. Globalisation
typically refers to the period from the early 1970s to the present, when
countries around the world saw large increases in the flows of goods,
services, and capital across borders. It is widely thought by political
economists that economic integration is welfare-improving on net and in
the long-run, yet even staunch free market economists acknowledge that
economic integration raises the incomes of certain domestic groups and
lowers the incomes of other groups, at least in the short-run. For this
reason, globalisation has brought with it many notable examples of
political protest and social unrest. Yet, discontent around economic
globalisation has varied across time and space and there remains much
debate regarding the conditions under which domestic political processes
respond to economic globalisation in different ways.

Both the concept and the processes of globalization have had a dubious
impact on the popular political imagination. The ideology which this
very concept bears witness to is that globalisation is a process, a
noun, something which has descended on the system of nation-states from
the outside, causing rather than being caused by the actions of
policymakers. As such, the very concept represents a political bias
because the casting of human actions as a process, the replacement of
verbs with nouns ending in “-ation”, is a tendency higlighted by
critical discourse analysts of authority figures seeking to obscure the
reality of their power [Fowler 1979, 33-41].[^nouns] It is well documented
that politicians strategically deploy the rhetoric of globalization to
justify economic reform [@Hay:2011dh], and it has also been shown that
the rise of economic globalization weakens the tendency of voters to
hold politicians accountable for economic performance [@Hellwig:2007gn; @Hellwig:2007jr].

Thus, the economics, rhetoric, and politics of economic globalisation
since the 1970s appear at first glance quite consistent with the
economics, rhetoric, and politics of the media at that time. If the
disappearance of propaganda theories during and after the war
represented, as I argued above, not the decline of that idea but rather
its implementation, then it would stand to reason that the role of media
in promoting state interests appears to have played a role in the
popular and scholarly narrative of economic globalisation since the
1970s. Specifically, the overarching thesis of this volume–which remains
too abstract and provisional to permit rigorous direct testing, but
which the present studies begin to make tractable–is that the rise of
modern media around the world has, in different ways, helped state
elites to promote certain perceptions of international integration to
fundamentally undemocratic ends.

## Pacification Goes Global

Since the end of the 1960s, in the short span of less than 50 years, we have observed the most rapid and geographically far-reaching *pacification* of humanity ever before witnessed in human history.
To detail what I mean, it is necessary to use different registers from different disciplines.
In terms of political attitudes, I have in mind the disppearance of *system-level opposition* in political issues (despite system-level dissatisfaction).
In terms of political behavior, I am most interested in the effective disppearance of *system-level contention*.
In sociological terms, this is noted as the increase in “anomie,” decrease of “trust,” and finally the depletion of “social capital.”
In philosophical terms, this means the global onset of “cynicism” and the failure of the last serious effort at Critical Theory.
In intellectual and emotional life more generally, this is the explosion of instrumental discourse at the cost of expressive discourse. 
This possibility of democratically, collectively controlling the institutions of our society would be crushed by the information revolution in the long-run, for the simple reason that the empowerment it generated was first enjoyed, and most effectively used, by precisely those most invested in the currently dominant institutions we might summarize as “global capitalism.” The institutional power of large state and corporate entites was so increased by the information revolution that it biased the thought and behavior of *more people*, across *larger distances*, and *more rapidly* than any scientific-technological change in the history of the world.
The reason the information revolution was so remarkable is because the science of information is the science of power. In this sense, it was not just a technological development (an increase in power) which increased the economic power of states and corporations, like the steam engine. The information revolution increased the power of power itself, by extending its efficiency and extending its reach to domains it never previously knew how to enter. This is why “globalization” and “mass media” modern finance, and the statistical sciences are all epi-phenomena of this same critical juncture of which our current lives are merely the hangover period.
The way it did this was by increasing the payoff to speaking and acting according to the rules of the current institutions, relative to the payoff of speaking and acting in system-level opposition to institutions. Because it increased the power of power, it forced those with lesser amounts of power to speak the dominant terms in order to achieve any goals whatsoever. And it paid them mightily for it. At the same time, it radically decreased the payoffs to those who preferred the longer-term goal of resisting the status quo temptations and fighting the radical fight for an even better society with fundamentally different institutions.
This is how the global radical currents of the late 1960s were so quickly transformed into speech and behavior compliant with global capitalism and its auxilliary institutions.
that the scientific understanding of information is almost completely monopolized in the hands of those who most benefit from the current arrangement of institutions. This is not to say that an elite cabal is in complete control, quite the contrary: the information revolution has directly empowered the institutions of global capitalism merely *through* the bodies and souls of those who most benefit from it. The information revolution has swept away its most privileged groups from their own power as much as it has swept away our collective political power to change the institutions. This is evidenced by the fact that almost all of the most powerful people in the world have the ethical and intellectual maturity of infants. They are literally too stupid to understand any ethical reality outside of that specific ethics which pays them. The reason the information revolution so completely changes the game is that the scientific understanding of information empowered the already ethically infantile money-seekers to not only abandon themselves in narrow self-interest, but to make the world over in their image. Specifically, it so increased the reach of exploitative capacity, and therefore so increased the profits available, that profit-seeking overtook the world in a sudden blast which we are still only trying to understand. The years from 1917 to today, but in particular the years from 1960 to today, so increased the reach of exploitation, into minds as well across global distances, that it completely changed our entire ethical perspective, but we continue to use old categories enforced by precisely those people whose profits have exploded and who have given themselves the right to change a great deal…
Information power is basically the power behind power itself: with the information revolution, the dominant institutions now protect and extend themselves through an evolutionary logic. Though if this saddens you, it is only because you’re addicted to the idea of power…

## Another way to see the puzzle is to compare globalizations

Another way to look at the puzzle is to consider how, in the first wave of globalization from 1870-1920, there was massive and militant worker resistance. This is the high time of the Second International, militant trade unionism such as the IWW, and sometimes terroristic, organized anarchism. Also great migrations and movement.
Today’s globalization is largely a globalization without people, where migration is not nearly as free as it once was (though of course there are what Saskia Sassen calls “counter-geographies” of globalization composed of often illicit population movements), and where worker resistance is not nearly what it was in the previous period most comparable in terms of global economic change. Comparing globalization today with the previous period is another way to motivate the puzzle: if the main precedent for globalization seems to entail massive popular movement of various sorts, how is it that today’s globalization has proceeded without similar popular tumult?


[^nouns]: Interestingly, it is also a tendency of social scientists (Billig
    117).