---
title: 'The Pacification of the World: Notes on the Politics of Information and Communication'
author: 'Justin Murphy'
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "testing this is the abstract."
output:
  html_document:
    toc: yes
    toc_depth: 3
    theme: readable
    keep_md: yes
  pdf_document:
    fig_caption: yes
    includes:
      in_header: mystyles.sty
      before_body: prefix.tex
    keep_tex: yes
    latex_engine: xelatex
    toc: yes
citecolor: red
fontsize: 12pt
geometry: margin=1.5in
linkcolor: red
mainfont: PT Serif
classoption: book
bibliography: mybib.bib
urlcolor: red
---



```{r, echo=FALSE}
setwd("~/Dropbox/gh_projects/pacification_of_the_world")
```

# Part 1: General Theoretical Reflections
```{r general-theory, child="~/Dropbox/gh_projects/pacification_of_the_world/content/general_theory.Rmd"}
```


# Part 2: Historical Outline
```{r empirics, child="~/Dropbox/gh_projects/pacification_of_the_world/content/history.Rmd"}
```


# Part 3: Other Topics
```{r topics, child="~/Dropbox/gh_projects/pacification_of_the_world/content/topics.Rmd"}
```




\pagebreak

# References




